workflows:
  ios-workflow:
    name: 'Sculpted Ice Explorer'
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: SculptedExplorerAPIKey
    environment:
      xcode: '26.0'
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ksafdkmkskald.sculptedexplorer
      vars:
        BUNDLE_ID: com.ksafdkmkskald.sculptedexplorer
        XCODE_WORKSPACE: SculptedExplorer.xcworkspace
        XCODE_SCHEME: SculptedExplorer
        APP_STORE_APPLE_ID: 6783732353
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Clean Pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up provisioning profile settings on  Xcode project
        script: |
          cd ios
          xcode-project use-profiles
      - name: Increment build number
        script: |
          cd ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/SculptedExplorer/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST || \
          $PLIST_BUDDY -c "Set :ITSAppUsesNonExemptEncryption false" $PLIST
      - name: Build IPA for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData//Build//*.app
      - $HOME/Library/Developer/Xcode/DerivedData//Build//*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
        copyright: 'Ramon Gomes'
