workflows:
  react-native-ios:
    name: Sculpted Ice Explorer
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: SculptedExplorerAPIKey
    environment:
      xcode: '26.0'
      vars:
        XCODE_WORKSPACE: 'SculptedExplorer.xcworkspace'
        XCODE_SCHEME: 'SculptedExplorer'
        BUNDLE_ID: 'com.ksafdkmkskald.sculptedexplorer'
        APP_STORE_APP_ID: 6783732353
    scripts:
      - name: Install npm dependencies
        script: npm install --force
      - name: Clean Pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
      - name: Install CocoaPods dependencies
        script: cd ios && pod install
      - name: Set up keychain for code signing
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: keychain add-certificates
      - name: Set up code signing settings in Xcode project
        script: xcode-project use-profiles --warn-only
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/SculptedExplorer/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST || \
          $PLIST_BUDDY -c "Set :ITSAppUsesNonExemptEncryption false" $PLIST
      - name: Build IPA for distribution
        script: xcode-project build-ipa --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME" --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
        copyright: 'Ramon Gomes'
