export const Colors = {
  arcticNavy: '#0D66A6',
  deepIceBlue: '#1392EC',
  oceanBlue: '#2B9DEE',
  brightArctic: '#66BFFF',
  crystalCyan: '#99D5FF',
  iceGlow: '#CCEAFF',
  frostWhite: '#E6F5FF',
  sculpturalRed: '#E8342F',
  deepRed: '#9F171C',
  redHighlight: '#FF5A4D',
  solidCardNavy: '#1183D5',
  darkPanel: '#0F74BD',
  borderIce: '#66BFFF',
  textPrimary: '#F0FAFF',
  textSecondary: '#B3DFFF',
  mutedText: '#7BC2F5',
  cyanActive: '#66BFFF',
  iceGold: '#FFC857',
};
